name: generate feed

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Download latest jar
      run: |
        wget -qO clojars-rss.jar $(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
    - name: Generate feed
      run: java -cp clojars-rss.jar clojars_rss.main data/libs.edn docs/rss/feed.xml
    - name: Push changes
      run: |
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git config --local user.name 'GitHub Action'
        git config --local user.email 'github-action@users.noreply.github.com'
        git add .
        git diff --staged --quiet || git commit -m 'Update feed'
        git push origin master
