name: generate feed

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache .m2
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Install deps
      run: lein deps
    - name: Generate feed
      run: |
        lein run -m clojars-rss.main data/libs.edn data/libs.edn.tmp docs/feed.xml
        mv data/libs.edn.tmp data/libs.edn
    - name: Push changes
      run: |
        git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        git config --local user.name 'GitHub Action'
        git config --local user.email 'github-action@users.noreply.github.com'
        git add .
        git diff --staged --quiet || git commit -m 'Update feed'
        git push origin master
