name: generate feed

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Download latest executable
      run: |
        wget -qO clojars-rss $(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
        chmod +x clojars-rss
    - name: Generate feed
      run: ./clojars-rss data/latest.edn data/stable.edn rss
    - name: Push changes
      run: |
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git config --local user.name 'GitHub Action'
        git config --local user.email 'github-action@users.noreply.github.com'
        git add data rss
        git commit -m 'Update feed'
        git push origin gh-pages
    - name: Generate summary
      run: |
        (
          echo '# Feed generation summary'
          echo
          echo "Updated at $(git show -s --format=%ci)"
          echo
          echo '## Feed updates'
          echo
          echo '| Feed | # of updates |'
          echo '| ---- | -----------: |'
          for target in stable latest; do
            n=$(git show --stat | grep data/$target.edn | awk '{ print $3/2 }')
            n=${n:-0}
            echo "| :white_check_mark: $target | $n |"
          done
          echo
          echo '## Feed links'
          echo
          echo '- [stable](https://athos.github.io/clojars-rss/rss/stable.xml)'
          echo '- [latest](https://athos.github.io/clojars-rss/rss/latest.xml)'
        ) > $GITHUB_STEP_SUMMARY

