name: generate feed

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Download latest executable
      run: |
        wget -qO clojars-rss $(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
        chmod +x clojars-rss
    - name: Generate feed
      run: ./clojars-rss data/latest.edn data/stable.edn rss
    - name: Push changes
      run: |
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git config --local user.name 'GitHub Action'
        git config --local user.email 'github-action@users.noreply.github.com'
        git add data rss
        git diff --staged --quiet || git commit -m 'Update feed'
        git push origin gh-pages
